### ISSUE TITLE
Task #6

### ISSUE THREAD

**Issue by jpwrobinson** [jpwrobinson/grazing-gradients#13]
stuff to do in August and September:

- [x]  James checking in with Andy Hoey stuff. Need more species (especially siganids)
- [x]  Sam, Jeneen, Jan: finish the modelling and predictions for hard coral + macroalgae + complexity

3 FGs * 3 effects = 3 plots with three lines each

- [x]  James to do fishing predictions

- [x] JAN define plot colours at the start of the script with HEX codes. Package wesanderson OR [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)

**Comment by jpwrobinson** [comment]
**Update on the bite rate stuff.** We probably can't use Sonia's videos (or anyone's videos) because these are best for measuring grazing pressure on benthos, but are bad at measuring individual fish feeding rates. Because fish move (wowza), videos can't capture the time spent _not_ feeding. Andy has in situ feeding obs that better capture feeding rates over a longer period of time (minutes not seconds), including movement between feeding patches ('forays').

Andy and his PhD student have feeding obs for acanthurids, siganids and scarids from GBR. Should be able to use these no problem.

**Comment by JanDajka** [comment]
Fish move... I have to go home and rethink my life.

**Comment by jpwrobinson** [comment]
a famous (white old) guy once said, counting fish is like counting trees, except they're invisible and keep moving

**Comment by JanDajka** [comment]
Pauly?

**Comment by JanDajka** [comment]
Who isn't white at all. Hahaha, damn.

**Comment by jpwrobinson** [comment]
Yoooo guys. Yooooooooooo guys.

I've updated our modelling Rmarkdown with model diagnostics and figures for GRAZERS. The document now fits a linear mixed effects model and examines fitted relationships for each covariate. The predictions have no uncertainty or errors, which is really annoying, but pretty normal because we're using random effects. There are also wordy things that describe the patterns.

If you pull the changes and open up [this file](https://github.com/jpwrobinson/grazing-gradients/blob/master/writing/models/01_biomass_models.Rmd) in RStudio, then **knit to HTML**, you should everything I've done.

Next step is to repeat these analyses for the other 2 functional groups. Jan and Sam are away and busy, so I just want to keep everyone in the loop here. Me and Jeneen will tackle this next week (right @Jeneen ?! more baklava?)

Still waiting on Andy Hoey's bite video data, but should be any day now.

**Comment by Jeneen** [comment]
Meet at Thursday 10am for whoever can make it via Skype?
-------- Original message --------From: James Robinson <notifications@github.com> Date: 14/09/2018  11:52  (GMT+00:00) To: jpwrobinson/grazing-gradients <grazing-gradients@noreply.github.com> Cc: Jeneen <jeneenhh@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [jpwrobinson/grazing-gradients] Task #6 (#13) 
Yoooo guys. Yooooooooooo guys.
I've updated our modelling Rmarkdown with model diagnostics and figures for GRAZERS. The document now fits a linear mixed effects model and examines fitted relationships for each covariate. The predictions have no uncertainty or errors, which is really annoying, but pretty normal because we're using random effects. There are also wordy things that describe the patterns.
If you open up this file and knit the HTML file, you should everything I've done.
Next step is to repeat these analyses for the other 2 functional groups. Jan and Sam are away and busy, so I just want to keep everyone in the loop here. Me and Jeneen will tackle this next week (right @Jeneen ?! more baklava?)
Still waiting on Andy Hoey's bite video data, but should be any day now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jpwrobinson/grazing-gradients","title":"jpwrobinson/grazing-gradients","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jpwrobinson/grazing-gradients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jpwrobinson in #13: Yoooo guys. Yooooooooooo guys.\r\n\r\nI've updated our modelling Rmarkdown with model diagnostics and figures for GRAZERS. The document now fits a linear mixed effects model and examines fitted relationships for each covariate. The predictions have no uncertainty or errors, which is really annoying, but pretty normal because we're using random effects. There are also wordy things that describe the patterns.\r\n\r\nIf you open up [this file](https://github.com/jpwrobinson/grazing-gradients/blob/master/writing/models/01_biomass_models.Rmd) and **knit the HTML** file, you should everything I've done.\r\n\r\nNext step is to repeat these analyses for the other 2 functional groups. Jan and Sam are away and busy, so I just want to keep everyone in the loop here. Me and Jeneen will tackle this next week (right @Jeneen ?! more baklava?)\r\n\r\nStill waiting on Andy Hoey's bite video data, but should be any day now."}],"action":{"name":"View Issue","url":"https://github.com/jpwrobinson/grazing-gradients/issues/13#issuecomment-421319968"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jpwrobinson/grazing-gradients/issues/13#issuecomment-421319968",
"url": "https://github.com/jpwrobinson/grazing-gradients/issues/13#issuecomment-421319968",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jpwrobinson/grazing-gradients] Task #6 (#13)",
"sections": [
{
"text": "",
"activityTitle": "**James Robinson**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jpwrobinson",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jpwrobinson/grazing-gradients\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jpwrobinson/grazing-gradients\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jpwrobinson/grazing-gradients/issues/13#issuecomment-421319968"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 369012544\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by JanDajka** [comment]
Sorry for my absence folks, been a bit turbulent here - I'll do my best to make it!

**Comment by JanDajka** [comment]
Will be there for Skype today folks!

**Comment by Jeneen** [comment]
James suggested 11 instead... does that still work for you Jan?

**Comment by JanDajka** [comment]
Yip, no worries.
