### ISSUE TITLE
no email yet from Mendeley....

### ISSUE THREAD

**Issue by samanthajh** [jpwrobinson/grazing-gradients#4]

**Comment by jpwrobinson** [comment]
ditto! @Jeneen what is GOING ON?!

**Comment by samanthajh** [comment]
Totes got mine.... it went to junk for some reason...

**Comment by Jeneen** [comment]
Weird! I'll send it again... it seemed to work for Jan because he didn't have an account yet. Have you logged on to your mendeley? 
-------- Original message --------From: James Robinson <notifications@github.com> Date: 17/05/2018  09:01  (GMT+00:00) To: jpwrobinson/grazing-gradients <grazing-gradients@noreply.github.com> Cc: Jeneen <jeneenhh@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [jpwrobinson/grazing-gradients] no email yet from Mendeley.... (#4) 
ditto! @Jeneen what is GOING ON?!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jpwrobinson/grazing-gradients","title":"jpwrobinson/grazing-gradients","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jpwrobinson/grazing-gradients"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jpwrobinson in #4: ditto! @Jeneen what is GOING ON?!"}],"action":{"name":"View Issue","url":"https://github.com/jpwrobinson/grazing-gradients/issues/4#issuecomment-389780211"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [jpwrobinson/grazing-gradients] no email yet from Mendeley.... (#4)","sections":[{"text":"","activityTitle":"**James Robinson**","activityImage":"https://avatars0.githubusercontent.com/u/5231402?s=160\u0026v=4","activitySubtitle":"@jpwrobinson","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"jpwrobinson/grazing-gradients\",\"issueId\":4,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"jpwrobinson/grazing-gradients\",\"issueId\":4}"},{"targets":[{"os":"default","uri":"https://github.com/jpwrobinson/grazing-gradients/issues/4#issuecomment-389780211"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":335974988}"}],"themeColor":"26292E"}

**Comment by jpwrobinson** [comment]
Ah I logged in and had an invite waiting. Thanks!
